---
# Configuration file for MegaLinter
# See all available variables at https://oxsecurity.github.io/megalinter/configuration/ and in linters documentation

# APPLY_FIXES: all
ENABLE_LINTERS:
    # Linter/Formatters in order of importance (imo)
    - COPYPASTE_JSCPD # Checks copy pasta
    - REPOSITORY_SECRETLINT # Prevent committing credentials
    - REPOSITORY_GIT_DIFF # Checks for any git conflict markers
    - YAML_PRETTIER # YAML formatter
    - YAML_YAMLLINT # YAML linter
    - SPELL_CSPELL # Code spellchecker. This one is pretty annoying, wouldn't be mad if no one used it
    - MARKDOWN_MARKDOWNLINT # Markdown linter
    - SPELL_MISSPELL # Detects misspellings

    # Security
    - REPOSITORY_SYFT # Generate a SBOM (software bill of materials)
    - REPOSITORY_TRIVY # SCA for everything Keep this commented until someone has the time to fix all the CVEs
    - REPOSITORY_DUSTILOCK # Protects against dependency confusion

# Exclude additional dirs/files that aren't included in the .gitignore file
FILTER_REGEX_EXCLUDE: '(\.githooks|\.template\.config|launchSettings.json|megalinter-reports)'

# Additional arguments for linters
REPOSITORY_SECRETLINT_ARGUMENTS: '--secretlintignore .gitignore "**/*"'
COPYPASTE_JSCPD_ARGUMENTS: '--gitignore --ignore "**/Migrations/*,**/ApiTests/*,*IntegrationTests/**"'
SPELL_CSPELL_ARGUMENTS: "--gitignore"
SPELL_CSPELL_FILE_EXTENSIONS: [".cs", ".js", ".tf", ".sh", ".css", ".html"]
REPOSITORY_TRIVY_ARGUMENTS: '--skip-dirs "ui/node_modules" --ignore-unfixed' # Would be nice if we could pass in gitignore :/

# General settings
PRINT_ALPACA: false
PRINT_ALL_FILES: false
SHOW_ELAPSED_TIME: true
SHOW_SKIPPED_LINTERS: true
# LOG_LEVEL: DEBUG
IGNORE_GITIGNORED_FILES: true

# Reporting
CLEAR_REPORT_FOLDER: true
EMAIL_REPORTER: false
FILEIO_REPORTER: false
GITLAB_COMMENT_REPORTER: false
JSON_REPORTER: false
GITHUB_STATUS_REPORTER: false
# REPORT_OUTPUT_FOLDER: none # Uncomment to turn off outputting reports
